### ISSUE TITLE
Menu Alignment

### ISSUE THREAD

**Issue by SHUBHAMDAVE001** [Totati/ngx-bootstrap-navbar#19]
I want to set the alignment of menus from left to right.
I have tried ul but it is not working.
Is there any possible way to changes it.

Thanks

Here are some pictures for representation

This is for mr-auto
![image](https://user-images.githubusercontent.com/16791576/135732396-5c5e6f8d-3498-48bf-aefd-18080a111a5c.png)
![image](https://user-images.githubusercontent.com/16791576/135732420-fcfa8686-8f42-4504-b161-2e92d1a717cc.png)

This is for ml-auto
![image](https://user-images.githubusercontent.com/16791576/135732431-1f482922-4ef3-43aa-a747-ace7d9af281b.png)
![image](https://user-images.githubusercontent.com/16791576/135732442-cdf4989a-31f3-490f-8cb9-7465f4dd87da.png)

**Comment by Totati** [comment]
Hi, thank you for your issue, however I have nothing to do with this. It's not a problem with the library itself. For me `ml-auto` is working, here you can see in my [right aligned bootstrap navbar example](https://stackblitz.com/edit/angular-bootstrap-dynamic-navbar-n3ecmc?file=app%2Fapp.component.html)

**Comment by SHUBHAMDAVE001** [comment]
Thank you for commenting.
Will check this issue one more time.
If I get stuck will let you know.

Thanks

**Comment by Totati** [comment]
Thank you.

**Comment by Totati** [comment]
@SHUBHAMDAVE001 Hi, did you check it? :)

**Comment by Totati** [comment]
Closed due to inactivity, submit new issue if still presents.
