### ISSUE TITLE
has no exported member 'ɵɵFactoryDeclaration'

### ISSUE THREAD

**Issue by vladimirpetukhov** [Totati/ngx-bootstrap-navbar#21]
Angular 11.0.0
"bootstrap": "^4.6.0"
Error: node_modules/ngx-bootstrap-navbar/lib/navbar-collapse.component.d.ts:11:21 - error TS2694: Namespace '"E:/CODE/.NET/CakeShopWeb/client/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

**Comment by Totati** [comment]
Which version are you using 0.0.x or 1.0.0?

**Comment by Totati** [comment]
Closing due lack of feedback, open a new issue if still presents.
