### ISSUE TITLE
navigation collapse only the predefiened break point

### ISSUE THREAD

**Issue by itshasnainkhanofficial** [Totati/ngx-bootstrap-navbar#3]
hi,
i want to collapse navigation on large screen or medium screen like in bootstrap we found navbar-expand-lg or navbar-expand-md .... so how to do it in this module?

**Comment by Totati** [comment]
Hello @Hasnainkhankqs . You can can remove the `ngxNavbarDynamicExpand` directive and add `navbar navbar-expand-lg` class to the nav element.
https://stackblitz.com/edit/angular-bootstrap-dynamic-navbar-jwewo1

**Comment by Totati** [comment]
Closed due to inactivity, submit new issue if still presents.
